// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjweuajrmyohatweqdts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtqd2V1YWpybXlvaGF0d2VxZHRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MDk2MjUsImV4cCI6MjA3NDA4NTYyNX0.37zOUBLqS3_FtUqboRW2VMdVMSjC-AQ56RBgdkHrsFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});